name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Main test
        run: |
          python -m unittest discover tests
  auto-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install pdoc
      - name: Run Pdoc
        run: |
          cd ..
          rm -rf classroom-voter/docs/*
          pdoc --html classrrom-voter --force
          cp html/classroom-voter/* classroom-voter/docs
          
